[project]
name = "tileops"
version = "0.0.1.dev0"
description = "TileOPs kernels for efficient inference"
authors = [{ name="Tile-AI" }]
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
dependencies = ["torch", "tilelang"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.yapf]
based_on_style = "yapf"
column_limit = 100
indent_width = 4

[tool.codespell]
ignore-words-list = "nd, te, ist, LOD, offen, NotIn, HSA"
skip = [
    "build",
    "3rdparty",
    "dist",
    ".venv"
]

[tool.setuptools]
packages = ["top"]

[project.urls]
"Homepage" = "https://github.com/tile-ai/tileops"
"Bug Tracker" = "https://github.com/tile-ai/tileops/issues"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    # "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    # "I",
]
ignore = [
    # Module level import not at top of file
    "E402",
    # star imports
    "F405", "F403",
    # ambiguous name
    "E741",
    # line too long
    "E501",
    # key in dict.keys()
    "SIM118",
    # memory leaks
    "B019",
    # No such file or directory
    "E902",
]